---
- name: test connection
  win_ping:

- name: Windows Deployment Services 
  win_feature:
    name: WDS
    state: present

- name: Setup WDS.
  win_shell: |
    wdsutil /initialize-server /remInst:"C:\RemoteInstall"  /standalone  | select -last 1
    wdsutil /Set-Server /UseDhcpPorts:No /DhcpOption60:Yes /AnswerClients:All 
  args:
    creates: C:\RemoteInstall
  register: wds_setup


- name: Ensure WDSServer is running
  win_service:
    name: WDSServer
    start_mode: auto
    state: started